title: Disk Management:Settings
description: Use this configuration to install disk management settings on the device.
payload:
  declarationtype: com.apple.configuration.diskmanagement.settings
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: '15.0'
      allowed-enrollments:
      - supervised
      - local
      allowed-scopes:
      - system
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  apply: combined
payloadkeys:
- key: Restrictions
  type: <dictionary>
  presence: optional
  content: Defines the restrictions for disks
  subkeys:
  - key: ExternalStorage
    title: External Storage
    type: <string>
    presence: optional
    rangelist:
    - Allowed
    - ReadOnly
    - Disallowed
    combinetype: enum-last
    content: |-
      Specifies the mount policy for external storage:
      * Allowed - external storage that is read-write or read-only will be mounted.
      * ReadOnly - only external storage that is read-only will be automatically mounted. Note that external storage that is read-write will not be mounted read-only.
      * Disallowed - no external storage will be mounted.
  - key: NetworkStorage
    title: Network Storage
    type: <string>
    presence: optional
    rangelist:
    - Allowed
    - ReadOnly
    - Disallowed
    combinetype: enum-last
    content: |-
      Specifies the mount policy for network storage:
      * Allowed - network storage that is read-write or read-only will be mounted.
      * ReadOnly - only network storage that is read-only will be mounted. Note that network storage that is read-write will not be mounted read-only.
      * Disallowed - no network storage will be mounted.
